#!/usr/bin/env bash
# Assemble setup.yaml (all scaffolding the notebook applies in Part 0) from manifests/.
# Policies that ARE the demo (50-, 52-, 55-, 61-) are NOT included; the notebook applies those.
# 51-mcp-jwt.yaml (the MCP route only accepts STS-minted tokens) is scaffolding and IS included.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/00-env.sh   # AGENT_IMAGE, MCP_IMAGE, CLUSTER_NAME (override any of them in your shell)
{
  echo "# Generated by scripts/build-setup.sh from manifests/ -- do not edit by hand."
  for f in manifests/00-namespaces.yaml manifests/05-keycloak.yaml manifests/10-mcp-server.yaml manifests/12-probes.yaml \
           manifests/11-agent.yaml manifests/13-shadow-agent.yaml manifests/14-clearance-agent.yaml manifests/31-model-catalog.yaml manifests/20-waypoint.yaml manifests/21-agents-waypoint.yaml manifests/30-llm-egress.yaml \
           manifests/40-mcp-backend.yaml manifests/51-mcp-jwt.yaml manifests/70-ingress.yaml manifests/71-ingress-oidc.yaml manifests/72-ingress-rescope.yaml manifests/80-tracing.yaml manifests/60-llm-budget-enforcement.yaml; do
    echo "---"; echo "# ---- $f"; envsubst '$MCP_IMAGE $AGENT_IMAGE $CLUSTER_NAME' < "$f"
  done
} > setup.yaml
echo "wrote setup.yaml ($(grep -c '^kind:' setup.yaml) resources; agent ${AGENT_IMAGE}, mcp ${MCP_IMAGE}, cluster ${CLUSTER_NAME})"
